---
# - hosts: all
#   any_errors_fatal: true
#   roles:
#     - glusterfs-client

# - hosts: gfs-cluster
#   any_errors_fatal: true
#   roles:
#     - glusterfs-server

- hosts: kube-master
  any_errors_fatal: true
  roles:
    - helm
    #- ark
    - metallb
    - nginx-ingress
    - cert-manager
    - duckdns
    #- dashboard
    #- openvpn
    #- unifi
    #- port-forwarding