---
- hosts: kube-master
  any_errors_fatal: true
  roles:
    - helm
    - metrics-server
    #- ark
    - metallb
    - nginx-ingress
    - cert-manager
    - duckdns
    - dashboard
    - rook
    - monitoring
    - pihole
    - nextcloud