---
- hosts: kube-master
  any_errors_fatal: true
  roles:
    - helm
    #- ark
    - metallb
    - nginx-ingress
    - cert-manager
    - duckdns
    #- dashboard
    #- openvpn
    #- unifi
    #- port-forwarding

- hosts: rook-cluster
  any_errors_fatal: true
  roles:
    - rook