---
- hosts: all
  any_errors_fatal: true
  roles:
    - arch-upgrade

- hosts: all
  any_errors_fatal: true
  roles:
    - cni-plugins

- hosts: all
  any_errors_fatal: true
  roles:
    - kubernetes-binaries

- hosts: kube-master
  any_errors_fatal: true
  roles:
    - upgrade-master

- hosts: kube-node
  roles:
    - upgrade-worker

- hosts: kube-master
  any_errors_fatal: true
  roles:
    - weave-net

- hosts: all
  any_errors_fatal: true
  roles:
    - prometheus-node-exporter

- hosts: all
  any_errors_fatal: true
  roles:
    - reboot

- import_playbook: deploy.yml
