---
- name: disable ACT (green) LED
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^dtparam=act_led_trigger', line: 'dtparam=act_led_trigger=none' }
    - { regexp: '^dtparam=act_led_activelow', line: 'dtparam=act_led_activelow=off' }