---
- name: create metallb-system namespace
  shell: >
    kubectl 
    create namespace metallb-system --dry-run -o yaml |
    kubectl
    apply -f -

- name: template metallb config
  template:
    src: ./metallb-values.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install metallb
  shell: >
    kubectl 
    apply -f https://raw.githubusercontent.com/google/metallb/{{ metallb_version }}/manifests/metallb.yaml

- name: config metallb
  shell: >
    kubectl 
    apply -f /tmp/metallb-values.yml

- name: create memberlist-secret (if not exists)
  block:
    - name: check for memberlist-secret
      shell: >
        kubectl
        get secret memberlist -n metallb-system
  rescue:
    - name: create memberlist-secret
      shell: openssl rand -base64 128 | kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey=-