---
- name: upgrade node
  become: yes
  become_user: root
  shell: >
    kubeadm upgrade node
    
- name: restart kubelet
  become: yes
  become_user: root
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
