apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dummy-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ duckdns_subdomains }}.duckdns.org
    secretName: {{ duckdns_subdomains }}-duckdns-tls
  rules:
  - host: {{ duckdns_subdomains }}.duckdns.org