---
- name: install BASH
  become: yes
  become_user: root
  pacman:
    name:
      - bash
      - bash-completion
    state: present

- name: set BASH as user shell
  become: yes
  become_user: root
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /bin/bash