---
- name: update helm repo
  shell: >
    helm repo update

- name: create monitoring namespace
  shell: >
    kubectl 
    create namespace monitoring --dry-run -o yaml |
    kubectl
    apply -f -
    
- name: template prometheus values.yml
  template:
    src: ./prom-values.yml
    dest: /tmp/prom-values.yml
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: upgrade prometheus (install if not exist)
  shell: >
    helm upgrade --install 
    -f /tmp/prom-values.yml prometheus stable/prometheus -n monitoring

- name: template kube-state-metrics values.yml
  template:
    src: ./kube-state-metrics-values.yml
    dest: /tmp/kube-state-metrics-values.yml
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: upgrade kube-state-metrics (install if not exist)
  shell: >
    helm upgrade --install 
    -f /tmp/kube-state-metrics-values.yml kube-state-metrics stable/kube-state-metrics -n monitoring

- name: template grafana values.yml
  template:
    src: ./grafana-values.yml
    dest: /tmp/grafana-values.yml
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: upgrade grafana (install if not exist)
  shell: >
    helm upgrade --install 
    -f /tmp/grafana-values.yml grafana stable/grafana -n monitoring

- name: template alertmanager-bot
  template:
    src: ./alertmanager-bot.yml
    dest: /tmp/alertmanager-bot.yml
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: create alertmanager-bot
  shell: >
    kubectl 
    apply -f /tmp/alertmanager-bot.yml