---
- name: upgrade control-plane
  become: yes
  become_user: root
  shell: kubeadm upgrade apply --yes {{ k8s_version }}
  retries: 3
  delay: 10

- name: upgrade node
  become: yes
  become_user: root
  shell: >
    kubeadm upgrade node 
    
- name: restart kubelet
  become: yes
  become_user: root
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: create config directory
  file:
    path: "{{ansible_env.HOME}}/.kube/"
    state: directory
    owner: "{{ansible_env.USER}}"
    group: "users"
    mode: 0755

- name: copy admin.conf
  become: yes
  become_user: root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ansible_env.HOME}}/.kube/config"
    owner: "{{ansible_env.USER}}"
    group: "users"
    mode: 0755
    remote_src: yes