---
- name: install acpid
  become: yes
  become_user: root
  pacman:
    name: acpid
    state: present

- name: enable acpid
  become: yes
  become_user: root
  service:
    name: acpid.service
    enabled: yes 
    state: started