---
- name: enable systemd-resolved
  become: yes
  become_user: root
  service:
    name: systemd-resolved.service
    enabled: yes 
    state: started

- name: Ensures /etc/systemd/resolved.conf.d/ dir exists
  become: yes
  become_user: root
  file: 
    path: /etc/systemd/resolved.conf.d/ 
    state: directory

- name: copy fallback_dns.conf
  become: yes
  become_user: root
  template:
    src: fallback_dns.conf
    dest: /etc/systemd/resolved.conf.d/fallback_dns.conf