---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cronjob
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      labels:
        app: cronjob
    spec:
      template:
        metadata:
          labels:
            app: cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: cronjob
              image: {{ curl_image_repository }}:{{ curl_image_tag}}
              imagePullPolicy: IfNotPresent
              command: [ "curl" ]
              args:
                - "--fail"
                - "-L"
                - "https://{{ duckdns_subdomains }}.duckdns.org/cron.php"
              resources:
                {}