---
- name: pull rook
  git:
    repo: https://github.com/rook/rook.git
    dest: /tmp/rook
    version: "{{ rook_release}}"
    force: yes

- replace:
    path: /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml
    regexp: '#(.*ROOK_CSI_CEPH_IMAGE.*)'
    replace: 'ROOK_CSI_CEPH_IMAGE: "{{ rook_csi_ceph_image }}"'

- replace:
    path: /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml
    regexp: '#(.*ROOK_CSI_RESIZER_IMAGE.*)'
    replace: 'ROOK_CSI_RESIZER_IMAGE: "{{ rook_csi_resizer_image }}"'

- replace:
    path: /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml
    regexp: '#(.*ROOK_CSI_REGISTRAR_IMAGE.*)'
    replace: 'ROOK_CSI_REGISTRAR_IMAGE: "{{ rook_csi_registrar_image }}"'
    
- replace:
    path: /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml
    regexp: '#(.*ROOK_CSI_PROVISIONER_IMAGE.*)'
    replace: 'ROOK_CSI_PROVISIONER_IMAGE: "{{ rook_csi_provisioner_image }}"'

- replace:
    path: /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml
    regexp: '#(.*ROOK_CSI_SNAPSHOTTER_IMAGE.*)'
    replace: 'ROOK_CSI_SNAPSHOTTER_IMAGE: "{{ rook_csi_snapshotter_image }}"'

- replace:
    path: /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml
    regexp: '#(.*ROOK_CSI_ATTACHER_IMAGE.*)'
    replace: 'ROOK_CSI_ATTACHER_IMAGE: "{{ rook_csi_attacher_image }}"'
  
- name: install rook (common.yaml)
  shell: >
    kubectl 
    apply -f /tmp/rook/cluster/examples/kubernetes/ceph/common.yaml

- name: install rook (operator.yaml)
  shell: >
    kubectl 
    apply -f /tmp/rook/cluster/examples/kubernetes/ceph/operator.yaml

- name: install rook (cluster.yaml)
  shell: >
    kubectl 
    apply -f /tmp/rook/cluster/examples/kubernetes/ceph/cluster.yaml
 
- name: create rook-ceph-block storageclass
  shell: >
    kubectl 
    apply -f /tmp/rook/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml

- name: create CephFilesystem
  shell: >
    kubectl 
    apply -f /tmp/rook/cluster/examples/kubernetes/ceph/filesystem.yaml

- name: create rook-cephfs storageclass
  shell: >
    kubectl 
    apply -f /tmp/rook/cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml

- name: make rook-ceph-block storageClass the default
  shell: >
    kubectl 
    patch storageclass rook-ceph-block -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

- name: template ceph dashboard ingress
  template:
    src: ./rook-ceph-dashboard-ingress.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"
  when: enable_rook_dashboard_ingress

- name: install ceph dashboard ingress
  shell: >
    kubectl apply 
    -f /tmp/rook-ceph-dashboard-ingress.yml
  when: enable_rook_dashboard_ingress