---
- name: update helm repo
  shell: >
    helm repo update

- name: create nginx-ingress namespace
  shell: >
    kubectl 
    create namespace nginx-ingress --dry-run -o yaml |
    kubectl
    apply -f -
    
- name: template nginx-ingress values.yml
  template:
    src: ./nginx-ingress-values.yml
    dest: /tmp/nginx-ingress-values.yml
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: upgrade nginx-ingress (install if not exist)
  shell: >
    helm upgrade --install 
    -f /tmp/nginx-ingress-values.yml nginx-ingress stable/nginx-ingress -n nginx-ingress