---
- name: upgrade all packages
  become: yes
  become_user: root
  pacman:
    update_cache: yes
    upgrade: yes

# Install base packages
- include: packages/yay.yml
- include: packages/bash.yml
  when: shell == 'bash'

- include: packages/zsh.yml
  when: shell == 'zsh'

# - include: packages/acpid.yml
- include: packages/htop.yml
- include: packages/dbus.yml
- include: packages/avahi.yml
# - include: packages/cups.yml
# - include: packages/cronie.yml
- include: packages/timesync.yml
# - include: packages/rsync.yml
- include: packages/ethtool.yml
- include: packages/socat.yml
- include: packages/ebtables.yml
- include: packages/docker.yml

- name: enable colorful output in pacman.conf
  become: yes
  become_user: root
  replace:
    path: /etc/pacman.conf
    regexp: '^#\s*Color.*$'
    replace: 'Color'

- name: disable 
  become: yes
  become_user: root
  replace:
    path: /etc/pacman.conf
    regexp: '^#\s*Color.*$'
    replace: 'Color'

- include: leds/act.yml
  when: act_led_disabled == 'true'

- include: leds/pwr.yml
  when: pwr_led_disabled == 'true'