---
- name: upgrade all packages
  become: yes
  become_user: root
  pacman:
    update_cache: yes
    upgrade: yes

# Install base packages
- include: arch/packages/yay.yml
- include: arch/packages/bash.yml
  when: shell == 'bash'

- include: arch/packages/zsh.yml
  when: shell == 'zsh'

# - include: arch/packages/acpid.yml
- include: arch/packages/htop.yml
- include: arch/packages/dbus.yml
- include: arch/packages/avahi.yml
# - include: arch/packages/cups.yml
# - include: arch/packages/cronie.yml
- include: arch/packages/timesync.yml
# - include: arch/packages/rsync.yml
- include: arch/packages/ethtool.yml
- include: arch/packages/socat.yml
- include: arch/packages/ebtables.yml
- include: arch/packages/docker.yml

- name: enable colorful output in pacman.conf
  become: yes
  become_user: root
  replace:
    path: /etc/pacman.conf
    regexp: '^#\s*Color.*$'
    replace: 'Color'