---
- name: install cert-manager
  shell: >
    kubectl apply 
    -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml

- name: template letsencrypt-staging ClusterIssuer
  template:
    src: ./letsencrypt-staging.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: template letsencrypt-prod ClusterIssuer
  template:
    src: ./letsencrypt-prod.yml
    dest: /tmp/
    owner: "{{ansible_env.USER}}"
    group: "{{ansible_env.USER}}"

- name: install letsencrypt-staging ClusterIssuer
  shell: >
    kubectl apply 
    -f /tmp/letsencrypt-staging.yml
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 60

- name: install letsencrypt-prod ClusterIssuer
  shell: >
    kubectl apply 
    -f /tmp/letsencrypt-prod.yml
  retries: 10
  delay: 60
  register: task_result
  until: task_result.rc == 0