# Furhter configuration can be found at 
# https://github.com/helm/charts/blob/master/stable/grafana/values.yaml

adminUser: {{ grafana_admin_user }}
adminPassword: {{ grafana_admin_password }}

persistence:
  enabled: true
  storageClassName: rook-ceph-block

ingress:
  enabled: {{ enable_grafana_ingress }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /{{ grafana_subpath }}(/|$)(.*)
  hosts:
    - {{ duckdns_subdomains }}.duckdns.org
  tls:
    - hosts:
        - {{ duckdns_subdomains }}.duckdns.org
      secretName: grafana-tls

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/{{ grafana_subpath }}/"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/general
      - name: 'ceph'
        orgId: 1
        folder: 'Ceph'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/ceph
dashboards:
  ceph:
    ceph-cluster:
      gnetId: 2842
      datasource: Prometheus
    ceph-osd:
      gnetId: 5336
      datasource: Prometheus
    ceph-pools:
      gnetId: 5342
      datasource: Prometheus
  default:
    node-exporter:
      gnetId: 1860
      datasource: Prometheus

notifiers:
 notifiers.yaml:
   notifiers:
   - name: Telegram
     type: telegram
     uid: Telegram
     is_default: true
     settings:
       bottoken: {{ telegram_notifier_bottoken }}
       chatid: "{{ telegram_notifier_chatid }}"

downloadDashboardsImage:
  repository: {{ curl_image_repository }}
  tag: {{ curl_image_tag }}